package(default_visibility = ["//visibility:public"])
cc_library(
    name = "string_fields",
    srcs = ["string_fields.cpp"],
    hdrs = ["string_fields.h"],
    deps = [
        ":field_base",
    ],
)
cc_library(
    name = "field_base",
    srcs = ["field_base.cpp"],
    hdrs = ["field_base.h"],
)
